name: enrichkitpy
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - conda-forge::zenodo_get
  - tqdm
  - anaconda::pandas
  - scipy
  - statsmodels
  - gseapy=0.9.5
