name: enrichkitpy
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - blas=1.0=openblas
  - bottleneck=1.3.5
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2023.12.12
  - certifi=2023.11.17
  - cffi=1.16.0
  - charset-normalizer=2.0.4
  - colorama=0.4.6
  - cryptography=41.0.7
  - idna=3.4
  - libcxx=14.0.6
  - libffi=3.4.4
  - libopenblas=0.3.21
  - llvm-openmp=14.0.6
  - ncurses=6.4
  - numexpr=2.8.7
  - numpy=1.26.3
  - numpy-base=1.26.3
  - openssl=3.2.0
  - pandas=2.1.1
  - pip=23.3.1
  - pycparser=2.21
  - pyopenssl=23.2.0
  - pysocks=1.7.1
  - python=3.11.7
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - python-wget=3.2
  - pytz=2023.3.post1
  - readline=8.2
  - requests=2.31.0
  - setuptools=68.2.2
  - six=1.16.0
  - sqlite=3.41.2
  - tk=8.6.12
  - tqdm=4.66.1
  - tzdata=2023d
  - urllib3=1.26.18
  - wheel=0.41.2
  - xz=5.4.5
  - zenodo_get=1.3.4
  - zlib=1.2.13
